/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.practica_final_janp.Interfaces;

import es.medac.practica_final_janp.bd.ConsultasDatos;


/**
 *
 * @author pipoa
 */
public class InterfazSeleccionar extends javax.swing.JFrame {

    /**
     * Creates new form InterfazSeleccionar
     */
    public InterfazSeleccionar() {
        initComponents();
        
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
    }
    /**
     * Creamos objeto de la clase consultasDatos
     */
    ConsultasDatos c = new ConsultasDatos();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jB_menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonClientexDni = new javax.swing.JButton();
        jButtonVehiculoMatricula = new javax.swing.JButton();
        jButtonVehiculoMarcaModeloAnio = new javax.swing.JButton();
        jButtonReparacionMatricula = new javax.swing.JButton();
        jButtonClienteNombreApellido = new javax.swing.JButton();
        jButtonVehiculoMarcaModelo = new javax.swing.JButton();
        jButtonReparacionDni = new javax.swing.JButton();
        jButtonReparacionFecha = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CajaMostrarTexto = new javax.swing.JTextArea();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelAnio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel2.setText("Eliminar");

        jB_menu.setText("Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_menu)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jB_menu)
                .addGap(27, 27, 27))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClientexDni.setBackground(new java.awt.Color(255, 255, 204));
        jButtonClientexDni.setText("Consultar cliente x DNI");
        jButtonClientexDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientexDniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClientexDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 30));

        jButtonVehiculoMatricula.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVehiculoMatricula.setText("Consultar vehículo x matrícula");
        jButtonVehiculoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehiculoMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVehiculoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 30));

        jButtonVehiculoMarcaModeloAnio.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVehiculoMarcaModeloAnio.setText("Cons vclo x marca, mdlo y año");
        jButtonVehiculoMarcaModeloAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehiculoMarcaModeloAnioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVehiculoMarcaModeloAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 30));

        jButtonReparacionMatricula.setBackground(new java.awt.Color(255, 255, 204));
        jButtonReparacionMatricula.setText("Cons rep x matrícula de vclo");
        jButtonReparacionMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReparacionMatriculaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReparacionMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, 30));

        jButtonClienteNombreApellido.setBackground(new java.awt.Color(255, 255, 204));
        jButtonClienteNombreApellido.setText("Cons cliente x nombre y apllds");
        jButtonClienteNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteNombreApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClienteNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 200, 30));

        jButtonVehiculoMarcaModelo.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVehiculoMarcaModelo.setText("Cons vehículo x marca y mdlo");
        jButtonVehiculoMarcaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehiculoMarcaModeloActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVehiculoMarcaModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 190, 30));

        jButtonReparacionDni.setBackground(new java.awt.Color(255, 255, 204));
        jButtonReparacionDni.setText("Cons reparacion x dni");
        jButtonReparacionDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReparacionDniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReparacionDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 190, 30));

        jButtonReparacionFecha.setBackground(new java.awt.Color(255, 255, 204));
        jButtonReparacionFecha.setText("Cons reparacion x fecha");
        jButtonReparacionFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReparacionFechaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReparacionFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 190, 30));

        jTextField1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 60));

        jTextField2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 60));

        jTextField3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, 70));

        jTextField4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 70));

        jTextField5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 220, 60));

        jTextField6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 210, 60));

        jTextField7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 210, 70));

        jTextField8.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 210, 70));

        CajaMostrarTexto.setColumns(20);
        CajaMostrarTexto.setRows(5);
        jScrollPane1.setViewportView(CajaMostrarTexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 300, -1));

        jTextField9.setBackground(new java.awt.Color(51, 51, 255));
<<<<<<< HEAD
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 360, 110));
=======
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 360, 110));
>>>>>>> 61d403ddc314c763902275f46eabbd186b0add97

        jTextField10.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 400, 80));

        jLabel1.setText("DNI cliente: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 70, 20));
        jPanel1.add(jLabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 70, 20));
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 70, 20));
        jPanel1.add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel5.setText("Matrícula:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 70, 20));
        jPanel1.add(jLabelMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel6.setText("Marca: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 70, 20));
        jPanel1.add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel7.setText("Modelo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 70, 20));
        jPanel1.add(jLabelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel8.setText("Año reparación:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 90, 20));
        jPanel1.add(jLabelAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel9.setText("Fecha matriculación:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 120, 20));
        jPanel1.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientexDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientexDniActionPerformed

        CajaMostrarTexto.setText(c.SelectClienteDni(jLabelDni.getText()));
        
    }//GEN-LAST:event_jButtonClientexDniActionPerformed

    private void jButtonClienteNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteNombreApellidoActionPerformed
        CajaMostrarTexto.setText(c.SelectClienteNombre(jLabelNombre.getText(), jLabelApellidos.getText()));
    }//GEN-LAST:event_jButtonClienteNombreApellidoActionPerformed

    private void jButtonVehiculoMarcaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehiculoMarcaModeloActionPerformed
        CajaMostrarTexto.setText(c.SelectVehiculoMarcaModelo(jLabelMarca.getText(), jLabelModelo.getText()));
    }//GEN-LAST:event_jButtonVehiculoMarcaModeloActionPerformed

    private void jButtonReparacionDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReparacionDniActionPerformed
        CajaMostrarTexto.setText(c.SelectReparacionPorVehiculo(jLabelAnio.getText()));
    }//GEN-LAST:event_jButtonReparacionDniActionPerformed

    private void jButtonVehiculoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehiculoMatriculaActionPerformed
        CajaMostrarTexto.setText(c.SelectVehiculo(jLabelMatricula.getText()));
    }//GEN-LAST:event_jButtonVehiculoMatriculaActionPerformed

    private void jButtonVehiculoMarcaModeloAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehiculoMarcaModeloAnioActionPerformed
        CajaMostrarTexto.setText(c.SelectVehiculoMarcaModeloAnio(jLabelMarca.getText(), jLabelMarca.getText(),Integer.parseInt(jLabelAnio.getText())));
    }//GEN-LAST:event_jButtonVehiculoMarcaModeloAnioActionPerformed

    private void jButtonReparacionMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReparacionMatriculaActionPerformed
        CajaMostrarTexto.setText(c.SelectReparacionPorVehiculo(jLabelMatricula.getText()));
    }//GEN-LAST:event_jButtonReparacionMatriculaActionPerformed

    private void jButtonReparacionFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReparacionFechaActionPerformed
        CajaMostrarTexto.setText(c.SelectReparacionPorFecha(jLabelFecha.getText()));
    }//GEN-LAST:event_jButtonReparacionFechaActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSeleccionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CajaMostrarTexto;
    private javax.swing.JButton jB_menu;
    private javax.swing.JButton jButtonClienteNombreApellido;
    private javax.swing.JButton jButtonClientexDni;
    private javax.swing.JButton jButtonReparacionDni;
    private javax.swing.JButton jButtonReparacionFecha;
    private javax.swing.JButton jButtonReparacionMatricula;
    private javax.swing.JButton jButtonVehiculoMarcaModelo;
    private javax.swing.JButton jButtonVehiculoMarcaModeloAnio;
    private javax.swing.JButton jButtonVehiculoMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLabelAnio;
    private javax.swing.JTextField jLabelApellidos;
    private javax.swing.JTextField jLabelDni;
    private javax.swing.JTextField jLabelFecha;
    private javax.swing.JTextField jLabelMarca;
    private javax.swing.JTextField jLabelMatricula;
    private javax.swing.JTextField jLabelModelo;
    private javax.swing.JTextField jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
