/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.practica_final_janp.Interfaces;

import es.medac.practica_final_janp.bd.BorrarDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author pipoa
 */
public class InterfazEliminar extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInsertar
     */
    public InterfazEliminar() {
        initComponents();
        
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Boton_Salir = new javax.swing.JButton();
        JBinsertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jB_menu2 = new javax.swing.JButton();
        jCB_Tablas = new javax.swing.JComboBox<>();
        jLCliente_dni = new javax.swing.JLabel();
        jTCliente_dni = new javax.swing.JTextField();
        jTvehiculo_matricula = new javax.swing.JTextField();
        jLVehiculo_matricula = new javax.swing.JLabel();
        jLReparacion_idvehiculo = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTReparacion_idvehiculo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Salir.setBackground(new java.awt.Color(255, 0, 0));
        Boton_Salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Boton_Salir.setText("SALIR");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 130, 50));

        JBinsertar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JBinsertar.setText("Insert");
        JBinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBinsertarActionPerformed(evt);
            }
        });
        jPanel1.add(JBinsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ELIMINAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 24));

        jB_menu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jB_menu2.setText("Menu");
        jB_menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_menu2ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 160, 60));

        jCB_Tablas.setBackground(new java.awt.Color(255, 255, 204));
        jCB_Tablas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCB_Tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Vehiculo", "Reparacion" }));
        jCB_Tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_TablasActionPerformed(evt);
            }
        });
        jPanel1.add(jCB_Tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 40));

        jLCliente_dni.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLCliente_dni.setText("DNI");
        jPanel1.add(jLCliente_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jTCliente_dni.setBackground(new java.awt.Color(204, 255, 204));
        jTCliente_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCliente_dniActionPerformed(evt);
            }
        });
        jPanel1.add(jTCliente_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 180, 40));

        jTvehiculo_matricula.setBackground(new java.awt.Color(204, 255, 204));
        jTvehiculo_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTvehiculo_matriculaActionPerformed(evt);
            }
        });
        jPanel1.add(jTvehiculo_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 200, 40));

        jLVehiculo_matricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLVehiculo_matricula.setText("Matricula");
        jPanel1.add(jLVehiculo_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jLReparacion_idvehiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLReparacion_idvehiculo.setText("IDVehiculo");
        jPanel1.add(jLReparacion_idvehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        jTReparacion_idvehiculo.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(jTReparacion_idvehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 130, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 370, 180));

        jTextField1.setBackground(new java.awt.Color(0, 153, 255));
        jTextField1.setForeground(new java.awt.Color(51, 153, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 230));

        jTextField2.setBackground(new java.awt.Color(0, 102, 204));
        jTextField2.setText("jTextField2");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 310));

        jTextField3.setBackground(new java.awt.Color(0, 102, 153));
        jTextField3.setText("jTextField3");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        jTextField4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_menu2ActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_jB_menu2ActionPerformed

    private void jTCliente_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCliente_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCliente_dniActionPerformed

    private void jTvehiculo_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTvehiculo_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTvehiculo_matriculaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void JBinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBinsertarActionPerformed
        BorrarDatos b = new BorrarDatos();
        if(jCB_Tablas.getSelectedItem().equals("Cliente")) {
            b.borrarXdni(jTCliente_dni.getText());
        }else if (jCB_Tablas.getSelectedItem().equals("Vehiculo")){ 
            b.borrarXidVehiculo(Integer.parseInt(jTReparacion_idvehiculo.getText()));
        } else {
            b.borrarXmatricula(jTvehiculo_matricula.getText());
        }
        
        
    }//GEN-LAST:event_JBinsertarActionPerformed

    private void jCB_TablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_TablasActionPerformed
        // TODO add your handling code here:
        mostrar();
    }//GEN-LAST:event_jCB_TablasActionPerformed

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
       int opcion = JOptionPane.showConfirmDialog(InterfazEliminar.this, "¿Estas seguro que quieres cerrar la aplicación?",
                "Ventana salida.", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
        }
    
    }//GEN-LAST:event_Boton_SalirActionPerformed

    public void mostrar(){
        if (jCB_Tablas.getSelectedItem().equals("Cliente")) {
           
            jLCliente_dni.setVisible(true);
            jTCliente_dni.setVisible(true);
         
          
            jLVehiculo_matricula.setVisible(false);
            jTvehiculo_matricula.setVisible(false);
          
            jTReparacion_idvehiculo.setVisible(false);
            jLReparacion_idvehiculo.setVisible(false);
          
        }else if(jCB_Tablas.getSelectedItem().equals("Vehiculo")){
          
            jLCliente_dni.setVisible(false);
            jTCliente_dni.setVisible(false);
        
        
            jLVehiculo_matricula.setVisible(true);
            jTvehiculo_matricula.setVisible(true);
         
            jTReparacion_idvehiculo.setVisible(false);
            jLReparacion_idvehiculo.setVisible(false);
          
        }else if(jCB_Tablas.getSelectedItem().equals("Reparacion")){
           
            jLCliente_dni.setVisible(false);
            jTCliente_dni.setVisible(false);
          
          
            jLVehiculo_matricula.setVisible(false);
            jTvehiculo_matricula.setVisible(false);
       
            jTReparacion_idvehiculo.setVisible(true);
            jLReparacion_idvehiculo.setVisible(true);
         
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton JBinsertar;
    private javax.swing.JButton jB_menu2;
    private javax.swing.JComboBox<String> jCB_Tablas;
    private javax.swing.JLabel jLCliente_dni;
    private javax.swing.JLabel jLReparacion_idvehiculo;
    private javax.swing.JLabel jLVehiculo_matricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCliente_dni;
    private javax.swing.JTextField jTReparacion_idvehiculo;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTvehiculo_matricula;
    // End of variables declaration//GEN-END:variables
}
