/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package es.medac.practica_final_janp.Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author pipoa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle("Realizado por ALUMNOS MEDAC");
        setSize(500, 500);

        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jB_InterfazInsertar = new javax.swing.JButton();
        jB_InterfazEliminar = new javax.swing.JButton();
        jB_InterfazModificar = new javax.swing.JButton();
        jB_InterfazSeleccionar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        Boton_Salir = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_InterfazInsertar.setBackground(new java.awt.Color(255, 255, 204));
        jB_InterfazInsertar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jB_InterfazInsertar.setText("Insertar");
        jB_InterfazInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_InterfazInsertarActionPerformed(evt);
            }
        });
        jPanel1.add(jB_InterfazInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 170, 40));

        jB_InterfazEliminar.setBackground(new java.awt.Color(255, 255, 204));
        jB_InterfazEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jB_InterfazEliminar.setText("Eliminar");
        jB_InterfazEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_InterfazEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jB_InterfazEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 40));

        jB_InterfazModificar.setBackground(new java.awt.Color(255, 255, 204));
        jB_InterfazModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jB_InterfazModificar.setText("Modificar");
        jB_InterfazModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_InterfazModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jB_InterfazModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 170, 40));

        jB_InterfazSeleccionar.setBackground(new java.awt.Color(255, 255, 204));
        jB_InterfazSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jB_InterfazSeleccionar.setText("Seleccionar");
        jB_InterfazSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_InterfazSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(jB_InterfazSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 170, 40));

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 230, 60));

        jTextField2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 230, 60));

        jTextField3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 230, 60));

        jTextField4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 230, 60));

        jTextField5.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 300, 310));

        jTextField6.setBackground(new java.awt.Color(51, 153, 255));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 370, 340));

        Boton_Salir.setBackground(new java.awt.Color(255, 0, 0));
        Boton_Salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Boton_Salir.setText("SALIR");
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 150, -1));

        jTextField8.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 180, 50));

        jTextField9.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 200, 60));

        jTextField7.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 420, 380));

        jTextField10.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 110, 70, 160));

        jTextField11.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 50, 60, 290));

        jTextField12.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 360));

        jTextField13.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 40));

        jTextField14.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 90, 30));

        jTextField15.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_InterfazInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_InterfazInsertarActionPerformed
        // TODO add your handling code here:
        InterfazInsertar i = new InterfazInsertar();
        setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jB_InterfazInsertarActionPerformed

    private void jB_InterfazEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_InterfazEliminarActionPerformed
        // TODO add your handling code here:
        InterfazEliminar i = new InterfazEliminar();
        setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jB_InterfazEliminarActionPerformed

    private void jB_InterfazModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_InterfazModificarActionPerformed
        // TODO add your handling code here:
        InterfazModificar i = new InterfazModificar();
        setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jB_InterfazModificarActionPerformed

    private void jB_InterfazSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_InterfazSeleccionarActionPerformed
        // TODO add your handling code here:
        InterfazSeleccionar i = new InterfazSeleccionar();
        setVisible(false);
        i.setVisible(true);
    }//GEN-LAST:event_jB_InterfazSeleccionarActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
         int opcion = JOptionPane.showConfirmDialog(Menu.this, "¿Estas seguro que quieres cerrar la aplicación?",
                "Ventana salida.", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_Boton_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton jB_InterfazEliminar;
    private javax.swing.JButton jB_InterfazInsertar;
    private javax.swing.JButton jB_InterfazModificar;
    private javax.swing.JButton jB_InterfazSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
